### ISSUE TITLE
Content type für Artikel [Dev-20.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-firebase#2]
User story:
**As a** Dev
**I want** the article data model to include a key-value pair specifying the content type of that article
**So that** it can be displayed to the user in the app

Acceptance criteria:
_Given_ the issue spreadsheet is opened
_When_ a content type for an article is specified
_Then_ that content type is delivered in the article data model via Firebase

Description:
Extend Spreadsheet and Firebase Function for Issue/Article content type tag

Dependencies:
none

DoD Checklist:
- [ ] Acceptance criteria are met
- [ ] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by grollk** [comment]
Value for the content type should be implemented as an enumeration with the following symbols „Text“, „Audio“, „Video“, „Text+Audio“, „Text+Video“

**Comment by pfkeen** [comment]
@grollk & @constructive-news 
Are there any updates on where exactly these symbols should be placed?

**Comment by constructive-news** [comment]
not yet. we're hoping to have this next week on the same screen with the share & like icons

**Comment by DavidKeanu** [comment]
Hey @olierxleben wie ist der aktuelle Stand bei diesem Ticket? Wir haben ein Ticket, dass hiervon abhängt. Kannst du eine grobe Zeiteinschätzung geben?

**Comment by olierxleben** [comment]
Hey @DavidKeanu

our journalists now can select a contentType



![Image](https://user-images.githubusercontent.com/1403225/212848531-fb21e6f8-744a-4e1e-baf7-00bb2d0f7fad.png)


The article collection will now have a new field: articleContentType 

![Image](https://user-images.githubusercontent.com/1403225/212848654-34995586-e7f5-4e11-a4b3-18d167cd9ca4.png)

Notice: this is not migrated for the whole dataset, yet. Please check if field does exist for the moment.
